pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.aliyun.com/nexus/content/groups/public/' }
        maven { url "https://maven.aliyun.com/repository/public" }
    }
    plugins {
        id 'com.android.application' version '8.9.2'
        id 'com.android.library' version '8.9.2'
        id 'org.jetbrains.kotlin.android' version '2.1.0'
        id 'com.google.devtools.ksp' version '2.1.0-1.0.29'
    }
}

include ':app'
include ':assistsxkit'

def assistsComposite = new File(settingsDir, '../assists')
if (assistsComposite.isDirectory()) {
    includeBuild(assistsComposite) {
        dependencySubstitution {
            substitute module('com.github.ven-coder:assists-base') using project(':assists')
            substitute module('com.github.ven-coder:assists-mp') using project(':assists-mp')
            substitute module('com.github.ven-coder:assists-web') using project(':assists-web')
            substitute module('com.github.ven-coder:assists-ime') using project(':assists-ime')
            substitute module('com.github.ven-coder:assists-ime') using project(':assists-ime')
            substitute module('com.github.ven-coder:assists-log') using project(':assists-log')
        }
    }
}
