apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {
    compileSdk rootProject.ext.compileSdk
    defaultConfig {
        applicationId "com.ven.assistsx"
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        ndk {
            //noinspection ChromeOsAbiSupport
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }

    signingConfigs {
        debug {
            storeFile file('assistsx.jks')
            storePassword '123321'
            keyAlias '1'
            keyPassword '123321'
        }
        release {
            storeFile file('assistsx.jks')
            storePassword '123321'
            keyAlias '1'
            keyPassword '123321'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        dataBinding true
    }
    viewBinding {
        enabled = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(":assistsxkit")
    implementation "androidx.room:room-runtime:${rootProject.ext.roomVersion}"
    implementation "androidx.room:room-ktx:${rootProject.ext.roomVersion}"
    implementation "com.github.mrmike:ok2curl:${rootProject.ext.ok2curlVersion}"
    implementation "com.lzy.net:okgo:${rootProject.ext.okgoVersion}"
    implementation "com.squareup.okhttp3:logging-interceptor:${rootProject.ext.okhttpLoggingVersion}"
    implementation "androidx.appcompat:appcompat:${rootProject.ext.appcompatVersion}"
    implementation "androidx.constraintlayout:constraintlayout:${rootProject.ext.constraintlayoutVersion}"
    implementation "com.github.li-xiaojun:XPopup:${rootProject.ext.xpopupVersion}"
    implementation "com.google.android.material:material:${rootProject.ext.materialVersion}"
    implementation "androidx.recyclerview:recyclerview:${rootProject.ext.recyclerviewVersion}"
    implementation "com.github.bumptech.glide:glide:${rootProject.ext.glideVersion}"
    kapt "com.github.bumptech.glide:compiler:${rootProject.ext.glideVersion}"
    implementation "com.google.android.flexbox:flexbox:${rootProject.ext.flexboxVersion}"
    implementation "com.google.code.gson:gson:2.11.0"
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'com.caverock:androidsvg:1.4'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.tencent.bugly:crashreport:4.1.9.3'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
}
